'use client'

import './globals.scss'
import type { Metadata } from 'next'
import { useEffect, useState } from 'react'
import { Nunito } from 'next/font/google'

const inter = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const [ theme, setTheme ] = useState('LightMode')

  useEffect(() => {
    const themecolor = localStorage.getItem('ThemeColor')

    if (themecolor) {
      setTheme(themecolor)
    }
  }, [theme])

  return (
    <html lang="en">
      <body className={inter.className + ' ' + theme}>{children}</body>
    </html>
  )
}
